---
# tasks file for ansible-role-wireguard-easy
- name: Wireguard easy | Add standart ssh user
  ansible.builtin.user:
    name: "{{ wireguard_user }}"
  register: wireguard_created_users

- name: Wireguard easy | Ensure all directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: "{{ wireguard_dir_state }}"
    mode: 0700
    owner: "{{ wireguard_created_users.name }}"
    group: "{{ wireguard_created_users.name }}"
  with_items:
    - "{{ wireguard_path }}"
    - "{{ wireguard_path }}/config"

- name: Wireguard easy | Templating docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wireguard_path }}/docker-compose.yml"
    owner: "{{ wireguard_created_users.name }}"
    group: "{{ wireguard_created_users.name }}"
    mode: 0644

- name: Wireguard easy | Run Wireguard
  docker_compose:
    project_src: "{{ wireguard_path }}"
    state: "{{ wireguard_container_state }}"
